### ISSUE TITLE
Dokumentation in Corporate Design bringen

### ISSUE THREAD

**Issue by Symmetronic** [Symmetronic/jampps#100]
Besonders die Startseite ist leider ziemlich zerschossen. Da soll nur einmal das jampps-Logo angezeigt werden und die Überschrift soll in der Mitte der Seite, nicht am unteren Rand sein. Siehe auch:
https://github.com/Symmetronic/jampps/blob/master/organisation/Spielbeschreibung/Spielbeschreibung.pdf

**Comment by MaxFleur** [comment]
Die Spielbeschreibung ist anders gestaltet als die Designtemplates, die vorher angefertigt wurden. Daher ist die Dokumentation nach Anpassung der Schriftart im Corporate Design.
