### ISSUE TITLE
Snake ist unsichtbar in Minigame

### ISSUE THREAD

**Issue by paul-schreiber** [Symmetronic/jampps#78]

**Comment by PaulSchreiber96** [comment]
Fixed by Peter© by Pauls PC© with a00ded1e0d04ace1a09cd2dfbab9a5a5b2b06870

**Comment by paul-schreiber** [comment]
Fixed by Peter© by Pauls PC© with a00ded1e0d04ace1a09cd2dfbab9a5a5b2b06870
