### ISSUE TITLE
Selbsteinschätzung

### ISSUE THREAD

**Issue by Symmetronic** [Symmetronic/jampps#85]
Von jedem Einzelnen eine Einschätzung, wie die Arbeit im Team lief, wie viel man selbst gemacht hat. Schwierigkeiten und was lief gut?

**Comment by Symmetronic** [comment]
Siehe Doku der anderen Gruppe.

**Comment by Symmetronic** [comment]
Ich hab die Selbsteinschätzung verfasst.

**Comment by paul-schreiber** [comment]
Ist an Maxime verschickt.

**Comment by PeterEgermann** [comment]
An Maxime geschickt
